### ISSUE TITLE
Apply minor fixes.

### ISSUE THREAD

**Issue by Max-Kuzomko** [trigdog/commerce_shipstation#1]
The admin form field commerce_shipstation_bundle_field needs to hidden for now, since this functionality is not ready
We can add "configure: commerce_shipstation.shipstation_admin_form" to modue.info.yml file
A dependency of the drupal:image module needed, since the module relies on the image styles.
routing.yml needs work. But for now at least we need to replace _permission: 'administer commerce_shipment' by something like _access: 'TRUE'

**Comment by Max-Kuzomko** [comment]
@trigdog please find below the pull request:
https://github.com/trigdog/commerce_shipstation/pull/2

**Comment by trigdog** [comment]
Thanks, merged.
