### ISSUE TITLE
Fix bugs. Make some improvements.

### ISSUE THREAD

**Issue by Max-Kuzomko** [trigdog/commerce_shipstation#3]
I think we need to avoid using $_GET variable and get query parameters from Symfony\Component\HttpFoundation\Request instead.

Pagination doesn't work:
Looks like $count_result counts items based on a specific range of orders. To count all orders we need to clone the query object before a range is applied.

Page parameter needs validation - set it to the first page if it is higher than a number of all pages.

Before fetching an information about shipments we need to make sure that the order has it.
Please see: $shipments = $order->get('shipments')->getValue();

OrderStatus and ShippingMethod are NULL.

Got exception when the script tried to fetch an image of the product.

**Comment by Max-Kuzomko** [comment]
Please find below the PR:
https://github.com/trigdog/commerce_shipstation/pull/4

**Comment by trigdog** [comment]
Thanks, committed.
